name: Go Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22 # Change this to your Go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: |
          make test
          go tool cover -func=coverage.out | grep total | awk '{print $3}' > coverage.txt

      - name: Create coverage badge
        run: |
          COVERAGE=$(cat coverage.txt | sed 's/%//')
          curl -o badge.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"

      - name: Update README with badge
        run: |
          COVERAGE=$(cat coverage.txt | sed 's/%//')
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"
          sed -i '/!\[Coverage\](.*)/c\![Coverage]('${BADGE_URL}')' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
           mv badge.svg ./badges/coverage-badge.svg
          git add coverage-badge.svg
          git commit -m "style(badge): Update test coverage badge"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}
