name: Go Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: production
    env:
      STAGE_STATUS: ${{vars.STAGE_STATUS}}
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_PORT: ${{secrets.SERVER_PORT}}
      SERVER_READ_TIMEOUT: ${{secrets.SERVER_READ_TIMEOUT}}
      PREFORK: ${{secrets.PREFORK}}
      DATABASE: ${{secrets.DATABASE}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      MDB_DATABASE: ${{secrets.MDB_DATABASE}}
      MDB_USERNAME: ${{secrets.MDB_USERNAME}}
      MDB_PASSWORD: ${{secrets.MDB_PASSWORD}}
      MDB_COLLECTION_USERS: ${{secrets.MDB_COLLECTION_USERS}}
      MDB_COLLECTION_CITIES: ${{secrets.MDB_COLLECTION_CITIES}}
      MDB_COLLECTION_TRAVELS: ${{secrets.MDB_COLLECTION_TRAVELS}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      JWT_EXPIRE_HOUR_COUNT: ${{secrets.JWT_EXPIRE_HOUR_COUNT}}
      SMTP_SERVER: ${{secrets.SMTP_SERVER}}
      SMTP_PORT: ${{secrets.SMTP_PORT}}
      SMTP_USERNAME: ${{secrets.SMTP_USERNAME}}
      SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
      REDIS_ADDR: ${{secrets.REDIS_ADDR}}
      REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
      REDIS_DB: ${{secrets.REDIS_DB}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print
        run: echo  "$SMTP_PORT"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22 # Change this to your Go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: |
          go clean -testcache
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out | grep total | awk '{print $3}' > coverage.txt

      - name: Create coverage badge
        run: |
          COVERAGE=$(cat coverage.txt | sed 's/%//')
          curl -o badge.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"

      - name: Update README with badge
        run: |
          COVERAGE=$(cat coverage.txt | sed 's/%//')
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"
          sed -i '/!\[Coverage\](.*)/c\![Coverage]('${BADGE_URL}')' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv badge.svg ./badges/coverage-badge.svg
          git add ./badges/coverage-badge.svg
          git commit -m "style(badge): Update test coverage badge"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}
